import { steps, accounts, statuses } from './data.js';
import { state, getOrders } from './store.js';
import { icon, escapeHtml as esc, money } from './utils.js';
export const button=(label,action,kind='primary',extra='')=>`<button type="button" class="btn btn-${kind}" data-action="${action}" ${extra}>${label}</button>`;
export const actions=(next='next',label='İrəli',disabled=false)=>`<div class="form-actions">${button('Geri','back','secondary',state.busy?'disabled':'')}${button(state.busy?'<span class="spinner" aria-hidden="true"></span> Gözləyin…':label,next,'primary',(disabled||state.busy)?'disabled':'')}</div>`;
export const errorHtml=()=>`<div id="form-error" class="form-error" role="alert" ${state.error?'':'hidden'}>${esc(state.error)}</div>`;
export const heading=(title,description='',accent=false)=>`<div class="section-heading ${accent?'accent':''}"><h2 tabindex="-1" data-view-heading>${title}</h2>${description?`<p>${description}</p>`:''}</div>`;
export const notice=(text,kind='',symbol='info')=>`<div class="notice ${kind}">${icon(symbol)}<div>${text}</div></div>`;
export const languageChoices=(name,selected)=>`<div class="language-options">${[['en','gb','İngiliscə'],['az','az','Azərbaycanca']].map(([id,flag,title])=>`<label class="language-choice"><input class="sr-only" type="radio" name="${name}" value="${id}" ${selected===id?'checked':''}><img class="language-flag" src="./assets/flag-${flag}.svg" width="32" height="16" alt="" aria-hidden="true">${title}</label>`).join('')}</div>`;
export const statusBadge=(status,english=false)=>`<span class="status-badge ${status}">${statuses[status]?.[english?'en':'az']??''}</span>`;
export function accountVisual(a){return a.image?`<img class="account-image" src="./assets/${a.image}" alt="${esc(a.name)}" width="56" height="37">`:`<span class="currency-icon" aria-hidden="true">${{AZN:'₼',USD:'$',EUR:'€'}[a.currency]}</span>`;}
export function accountRow(a,{selectable=true,checked=false,show=false}={}){
  return `<${selectable?'label':'div'} class="account-row">${accountVisual(a)}<div class="account-copy"><div class="account-name">${a.name} <span class="muted">· ${a.last4}</span></div><div class="account-meta">${a.type==='account'?a.number:`${a.currency} · ABB`}${a.disabled?' · Filiala yaxınlaşın':''}</div><div class="account-balance">${show?money(a.balance,a.currency):`•••••• ${a.currency}`}</div></div>${selectable?`<input type="checkbox" name="account" value="${a.id}" aria-label="${a.name} ${a.last4}" ${checked?'checked':''} ${a.disabled?'disabled':''}>`:''}</${selectable?'label':'div'}>`;
}
export function renderHeader(){
  const nav=[['accounts','Hesablar'],['cards','Kartlar'],['payments','Ödənişlər'],['documents','Sənədlər'],['orders','Sifarişlərim']];
  return `<a class="brand" href="#/documents" aria-label="ABB — Ana səhifə"><img src="./assets/abb-logo.png" width="123" height="60" alt="ABB"></a><nav id="main-nav" class="main-nav" aria-label="Əsas naviqasiya">${nav.map(([route,name])=>`<a class="nav-link ${state.route===route?'active':''}" href="#/${route}" ${state.route===route?'aria-current="page"':''}>${name}</a>`).join('')}</nav><div class="header-actions"><button class="icon-button" type="button" data-action="notifications" aria-label="Bildirişlər">${icon('bell')}${getOrders().length?'<span class="notification-dot"></span>':''}</button>${state.authenticated?`<button type="button" class="profile" data-action="profile" aria-label="Profil"><span class="avatar">${state.customer.initials}</span><span class="profile-name">${esc(state.customer.name)}</span></button>`:''}<button type="button" class="icon-button menu-button" data-action="menu" aria-controls="main-nav" aria-expanded="false" aria-label="Menyu">${icon('menu')}</button></div>`;
}
export function stepper(){return `<ol class="stepper" aria-label="Sifariş mərhələləri">${steps.map((name,i)=>`<li class="step ${i+1<state.step?'complete':i+1===state.step?'active':''}" ${i+1===state.step?'aria-current="step"':''}><button type="button" data-action="jump" data-step="${i+1}" aria-label="${i+1}. ${name}" ${i+1>=state.step||state.step===7?'disabled':''}><span class="step-number">${i+1}</span><span class="step-label">${name}</span></button></li>`).join('')}</ol><div class="mobile-progress"><strong>${steps[state.step-1]}</strong><span>${state.step} / 7 addım</span></div>`;}
export function shell(content,{wizard=true,title='',description=''}={}){
  return `<div class="container"><nav class="breadcrumb" aria-label="Səhifə yolu"><a href="#/documents">Ana səhifə</a>${icon('chevron-right')}<a href="#/documents">Sənədlər</a>${icon('chevron-right')}<span>${wizard?steps[state.step-1]:title}</span></nav>${wizard?`<section class="intro"><div class="intro-copy"><h1>Rəqəmsal Sənəd Sifarişi</h1><p>Səfirliklər üçün tələb olunan hesab arayışı və çıxarışı onlayn tərtib edin, ödəyin və real vaxtda izləyin.</p></div><span class="delivery-badge">${icon('send')} Rəqəmsal göndəriş — birbaşa səfirliyə</span></section>${stepper()}`:heading(title,description)}<div class="view">${content}</div></div>`;
}
