import { documents, embassies, demoCustomer } from '../data.js';
import { state } from '../store.js';
import { actions, button, heading, errorHtml, notice, languageChoices } from '../components.js';
import { escapeHtml as esc, icon } from '../utils.js';
export function documentType(){return `${heading('Sənəd növünü seçin.','Hansı sənədi sifariş etmək istədiyinizi seçin. Hər iki sənəd rəqəmsal formada hazırlanacaq.')}<form id="document-form" class="document-panel"><fieldset class="fieldset"><legend class="sr-only">Sənəd növü</legend><div class="document-options">${Object.entries(documents).map(([id,doc])=>`<label class="document-card" for="type-${id}">${icon(id==='statement'?'file-text':'send','document-art')}<h3>${doc.title}</h3><p>${doc.description}</p><div class="document-price">${doc.price} AZN</div><input type="radio" id="type-${id}" name="document-type" value="${id}" ${state.draft.type===id?'checked':''} aria-label="${doc.title}"></label>`).join('')}</div></fieldset><div class="center-actions"><button type="button" class="btn btn-primary btn-wide" data-action="next">Davam et</button></div></form>`;}
export function embassy(){const d=state.draft;return `${heading(d.type==='reference'?'Səfirlik məlumatları':'Təqdim ediləcək yer','Sənədin təqdim olunacağı yeri və dilini seçin.')}<form id="embassy-form" class="stack">
 ${d.type==='statement'?`<fieldset class="fieldset"><legend>Təqdim ediləcək yer</legend><div class="choice-row">${[['embassy','Səfirlik'],['personal','Şəxsi istifadə'],['other','Digər qurum']].map(([id,t])=>`<label class="chip"><input class="sr-only" type="radio" name="destination" value="${id}" ${d.destination===id?'checked':''}>${t}</label>`).join('')}</div></fieldset>`:''}
 ${d.destination==='embassy'?`<div class="field"><label class="sr-only" for="embassy">Səfirlik</label><select id="embassy" name="embassy" class="select-control embassy-select">${embassies.map(e=>`<option value="${e.id}" ${d.embassy===e.id?'selected':''}>${e.name}</option>`).join('')}</select></div>`:d.destination==='other'?`<div class="field"><label for="recipient">Qurumun adı</label><input id="recipient" name="recipient" maxlength="120" placeholder="Qurumun adını daxil edin" value="${esc(d.recipient)}"></div>`:notice('Sənəd şəxsi istifadə üçün hazırlanacaq. Onu sifarişlərinizdən aça və PDF kimi saxlaya bilərsiniz.')}
 <fieldset class="fieldset"><legend>Sənədin dili</legend>${languageChoices('language',d.language)}</fieldset>${errorHtml()}${actions()}</form>`;}
export function fin(){return `<section class="panel auth-panel"><div class="auth-content"><div class="auth-title"><div><h2 tabindex="-1" data-view-heading>Kimliyinizi təsdiqləyin</h2><p>Hesab məlumatlarını göstərmək üçün FİN kodunuzu daxil edin.</p></div><button type="button" class="text-link" data-action="fin-help">FİN nədir? ${icon('circle-help')}</button></div><form id="fin-form" novalidate>${codeFields('fin',7)}${errorHtml()}${actions('verify-fin')}</form></div></section>`;}
export function otp(){return `<section class="panel auth-panel"><div class="auth-content"><div class="auth-title"><div><h2 tabindex="-1" data-view-heading>Təsdiqləmə kodu</h2><p>${demoCustomer.phone} nömrəsi üçün 6 rəqəmli kodu daxil edin.</p></div></div><form id="otp-form" novalidate>${notice('Bu, FİN kodunuzla ABB-də qeydiyyatdan keçmiş hesabınıza bağlı mobil nömrədir. Kod başqa nömrəyə göndərilə bilməz.')}${codeFields('otp',6)}${errorHtml()}<div class="resend-row"><span>Kod gəlməyib?</span><button class="text-link" type="button" data-action="resend" id="resend-button" ${Date.now()<state.otpDeadline?'disabled':''}>Yenidən göndər <span id="countdown"></span></button></div><p class="small muted">Bu nömrə aktiv deyil? <button type="button" class="text-link" data-action="phone-help">Ətraflı</button></p>${actions('verify-otp')}</form></div></section>`;}
function codeFields(name,count){return `<fieldset class="fieldset"><legend class="sr-only">${name==='fin'?'FİN kodu':'Təsdiqləmə kodu'}</legend><div class="code-fields ${name==='otp'?'otp-fields':''}" data-code="${name}">${Array.from({length:count},(_,i)=>`<input type="text" name="${name}-${i}" aria-label="${name==='fin'?'FİN simvolu':'Kod rəqəmi'} ${i+1}" maxlength="${count}" inputmode="${name==='otp'?'numeric':'text'}" autocomplete="${name==='otp'&&i===0?'one-time-code':'off'}" autocapitalize="characters" spellcheck="false" ${state.busy?'disabled':''} aria-describedby="form-error">`).join('')}</div></fieldset>`;}
